apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: NodePort
  selector:
    app: blog-nodejs-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8095
      nodePort: 30001
